server:
  port: 9090

spring:
  threads:
    virtual:
      enabled: false
  thread-executor: virtual
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: ${POSTGRES_CONNECTION_POOL:2}

    url: ${POSTGRES_CONNECT_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${POSTGRES_AUTO_DDL:create}

management:
  server:
    # different port for actuator endpoint. This might not be exposed outside of k8s cluster
    port: 9091
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always